In [19]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
import xlrd
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

#suppress annoying hartmless errors
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [20]:
loc = ("/Users/jakegrosek/Desktop/thinkful_py/Unit_3/heart.csv")
df = pd.read_csv("heart.csv")

In [21]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
# fills in NaN valeus with zero across the dataframe
df.fillna(0, inplace=True)

In [22]:
df.dtypes


age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [24]:
exang = df['exang']

KNN Regression

In [34]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=10)
X = df[['trestbps', 'sex', 'thalach']]
Y = exang
neighbors.fit(X,Y)
print("First test:")
print(neighbors.predict([[120, 1, 165]]))
print(neighbors.predict_proba([[120, 1, 165]]))

print("Second test:")
print(neighbors.predict([[140, 0, 165]]))
print(neighbors.predict_proba([[140, 0, 165]]))

First test:
[0]
[[ 0.9  0.1]]
Second test:
[0]
[[ 0.7  0.3]]


OLS Regression

In [36]:
regr = linear_model.LinearRegression()
regr.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [37]:
print('Coefficients: \n', regr.coef_)
print('Intercept: \n', regr.intercept_)

Coefficients: 
 [ 0.00154343  0.12967151 -0.00759828]
Intercept: 
 1.1720514569
